### ISSUE TITLE
Parameter types for `choice`, `ordinal`, `plural`, and `selectordinal`

### ISSUE THREAD

**Issue by drewhamilton** [cashapp/paraphrase#207]
Currently, an `Int` parameter is generated for `choice`, `ordinal`, `plural`, and `selectordinal` ICU argument types. I think this is too restrictive, but I'm not sure what the correct level of restriction should be.

My use case is a few `plural` strings that have a `Long` argument. The easiest solution would be to produce a `Long` parameter instead of `Int`. This would be annoying to probably the majority of consumers who are pluralizing with an `Int`.

ICU can handle any primitive number as input: It will happily choose `=9223372036854775807` if given `Long.MAX_VALUE`, or `=1.5` or `=1.7976931348623157E308` if given `1.5` or `Double.MAX_VALUE`, respectively. Maybe `Number` is the correct parameter type, then? It's nice that it would allow both `Int` or `Long`, but it feels less helpful when the vast majority of consumers (everyone?) would want a whole number.

**Comment by oldergod** [comment]
Would that work if we take `kotlin.Number` ?

**Comment by drewhamilton** [comment]
`Number` is the only type that would allow both `Int` or `Long`. And I believe any type of `Number` will technically work because ICU internally calls `toDouble`.

But it feels semantically unhelpful to allow things like `Float`, `Double`, `BigDecimal` for an ordinal argument. Does anyone want to intentionally print something like "I ate my 3.14th ice cream this week"? Feels like enabling a footgun that we currently don't enable.

I can also imagine the stance that `Int` is appropriately restrictive: For any number bigger than 2,147,483,647, it's likely more appropriate to implement more robust, user-friendly formatting: "I ate my 2,147,483,648th ice cream this week" vs. "I ate my 2 billionth ice cream this week". I'm not sure if the latter is difficult to achieve correctly, and also feel it's likely that this misses a valid use case.

**Comment by theisenp** [comment]
### Plurals
We should probably move to `Number`. Partially for longs, but mostly for decimals, which are explicitly supported by ICU and seem like they'd be a pretty common use case:
```
{length, plural,
  one {The race is 1 mile long}
  other {The race is # miles long}
}

// The race is 26.2 miles long
```
In English, decimal numbers always get the "Other" case, but in other languages it's different. In French, for example, everything in [0.0, 2.0) gets the "One" case.

Kind of surprised I missed this one before!

### Ordinals
My general thinking is that if it affects the output, you should be able to express it in Paraphrase.

So at a minimum I think it makes sense to support longs. If you really did want to say that you ate your 2,147,483,648th ice cream this week, that's how you would express it in the ICU format and it would be weird for Paraphrase to impose arbitrary restrictions on you.

I'm less sure about decimals. From a very quick test in English it seems like the decimal component of the number gets ignored. So if you format `{ice_creams, ordinal}` with `2.1` you get `2nd`. If that's true for all numbers and all locales then I think restricting to whole numbers could make sense. I think we need to dig into the library to see what's up.

**Comment by drewhamilton** [comment]
The formatters for each locale are supplied by the system (follow the logic inside [this private `MessageFormat` function](https://cs.android.com/android/platform/superproject/main/+/main:external/icu/icu4j/main/classes/core/src/com/ibm/icu/text/MessageFormat.java;l=2442;drc=a5edbd0aa6346a902dffe7f4340bf403dc87adb9;bpv=1;bpt=1) called at initialization), so it's impossible generalize when rounding is applied purely from ICU logic.

Of all `Locales.getAvailableLocales` on my JVM and on Android, Hindi-language locales are the only ones that don't round `2.1`. I'm not sure what to make of this; whether it's intentional or a bug.

```kotlin
import com.google.common.truth.Truth.assertThat
import com.ibm.icu.text.MessageFormat
import java.util.Locale
import org.junit.Test

class OrdinalTest {

  @Test fun ordinal() {
    Locale.getAvailableLocales().forEach { locale ->
      val formatted = formatOrdinal(2.1, locale)

      if (locale.language == "hi") {
        return@forEach
      }
      assertThat(formatted).doesNotContain("2.1")
    }
  }

  @Test fun hindiOrdinal() {
    val locale = Locale("hi")

    assertThat(formatOrdinal(3, locale)).isEqualTo("A 3रा B (hi)")
    assertThat(formatOrdinal(2.1, locale)).isEqualTo("A 2.1 B (hi)")
    assertThat(formatOrdinal(2, locale)).isEqualTo("A 2रा B (hi)")
    assertThat(formatOrdinal(1, locale)).isEqualTo("A 1ला B (hi)")
  }

  @Test fun englishOrdinal() {
    val locale = Locale("en")

    assertThat(formatOrdinal(3, locale)).isEqualTo("A 3rd B (en)")
    assertThat(formatOrdinal(2.1, locale)).isEqualTo("A 2nd B (en)")
    assertThat(formatOrdinal(2, locale)).isEqualTo("A 2nd B (en)")
    assertThat(formatOrdinal(1, locale)).isEqualTo("A 1st B (en)")
  }

  private fun formatOrdinal(value: Number, locale: Locale): String {
    val format = "A {value,ordinal} B ($locale)"
    val arguments = mapOf("value" to value)
    return MessageFormat(format, locale).format(arguments)
  }
}
```

**Comment by theisenp** [comment]
I think the rounding happens [here](https://github.com/unicode-org/icu/blob/706044b0a20ce0464a2c13950f1d875203b89a61/icu4j/main/classes/core/src/com/ibm/icu/text/NFRule.java#L815). When I step through in the debugger, `rulePatternFormat` is null for Hindi locales so it skips the case to `long`.

I'm inclined to think it's a bug rather than intentional? The [CLDR plural rule documentation](https://www.unicode.org/cldr/cldr-aux/charts/36.1/supplemental/language_plural_rules.html) doesn't include decimal numbers in the examples for ordinals in Hindi (or in any other language, as far as I can tell). And just as a [linguistic concept](https://en.wikipedia.org/wiki/Ordinal_numeral), ordinal numerals only seem to make sense for whole numbers. They deal with relative position, and you can't be the 2.5th person in line - you would just be 3rd. We could ask for confirmation either in the repo or on the [mailing list](https://sourceforge.net/p/icu/mailman/icu-support/) if we want to be sure.

That being said, it might not make much of a difference to us if we support both `Int` and `Long`. We would have a couple options:

#### Accept `Number` as the parameter type
- Ergonomic for both `Int` and `Long`
- Allows `Double` and `Float`, which isn't ideal, but ehhh maybe it's fine

#### Only accept `Long`
- Ergonomic for `Long`, have to convert `Int` which is annoying
- Doesn't allow `Double` or `Float`

#### Generate two methods, one that accepts `Int` another that accepts `Long`
- Ergonomic for both `Int` and `Long`
- Doesn't allow `Double` or `Float`
- Not consistent with how we handle other parameter types
- Can get weird if there's more than one ordinal arg in the string. Maybe have to do one method with all `Int` another with all `Long` to avoid combinatorial explosion of methods?

I'm leaning toward just using `Number` and not worrying about it unless it becomes an issue (which it likely won't, since I don't think ordinals are super common). But open to other ideas!

**Comment by theisenp** [comment]
`choice` also seems to support decimal numbers, so we might as well move it to `Number` as well:
```
{0, choice, 0#Zero | 0.5#Half | 1<{0,number}}
```

**Comment by drewhamilton** [comment]
Since your link to where it "rounds" shows a cast to a long, I thought to confirm that it never rounds up. And...

```kotlin
@Test fun englishOrdinal() {
  val locale = Locale("en")
  assertThat(formatOrdinal(2.8, locale)).isEqualTo("A 3nd B (en)")
}
```

**Comment by drewhamilton** [comment]
The first and the last, as you suggested earlier.

If one arg is an int and the other is a long, the consumer converting the int to a long for this one function call is not annoying-at-scale the way that needing to convert _all_ ordinal ints to longs would be.
